baseURL = "https://yuusuzumi.github.io/blog/"
languageCode = "ja"
title = "星屑の夜"
theme = "hugo_theme_robust"
themeDir = "themes"
hasCJKLanguage = true
canonifyurls = true
GoogleAnalytics = ""
disqusShortname = ""


[params]
  description = "備忘録と独り言など雑記"
  dateformat = "2006/01/02"

[params.author]
  thumbnail = ""
  name = "yuusuzumi"
  description = ""
  github = "https://github.com/yuusuzumi"

[outputs]
  page = ["HTML", "AMP"]

[permalinks]
  memo = "/:section/:title/"
  shopping = "/:section/:title/"
  trpg = ":section/:title/"
